entero n1, n2
cadena [30] correo
cadena [30] clave 
inicio
n2 <- 4
n1 <- 1
	mientras (n1 <= 3) haga 
	Escriba "ingrese su correo"
	llamar nueva_linea
	lea correo
	Escriba "ingrese su clave"
	llamar nueva_linea
	lea clave 
		si (correo = "kevin.com") y (clave = "123") entonces
		Escriba "bienvenido"
		n1 <- 3
		sino 
		Escriba "intenta de nuevo, tienes " ,  n1 + 1 , " intentos "
		llamar nueva_linea
		
		fin si
		n1 <- n1 + 1
	fin mientras

 
fin